#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me is redirecting to another page

echo 'Hello World!' > /var/www/html/index.nginx-debian.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://cuberule.com/;
    }
}" > /etc/nginx/sites-available/default
service nginx start