#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with
#+ a sleep 2 in between each iteration.
#   Displays "I am invincible!!!" in between each iteration

# Handle SIGTERM
trap "echo 'I am invincible!!!'" 15


# print the message forever
while true;
do
	echo "To infinity and beyond";
	sleep 2
done
